#!/bin/bash
# AppRun script for witnessd AppImage
# This script is executed when the AppImage is run

SELF=$(readlink -f "$0")
HERE=${SELF%/*}

# Set up environment
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${HERE}/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

# Determine which command to run
ARGV0=$(basename "$ARGV0")
case "$ARGV0" in
    witnessctl|witnessctl.AppImage)
        exec "${HERE}/usr/bin/witnessctl" "$@"
        ;;
    witnessd-ibus|witnessd-ibus.AppImage)
        exec "${HERE}/usr/bin/witnessd-ibus" "$@"
        ;;
    *)
        # Default to witnessd daemon
        exec "${HERE}/usr/bin/witnessd" "$@"
        ;;
esac
